### ISSUE TITLE
Error: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by vladMocan** [YOU54F/cypress-slack-reporter#1035]
Hello,

I'm getting this error when trying to run `npx cypress-slack-reporter --vcs-provider none --ci-provider none --verbose`

I'm trying to run it from my local machine, my slack webhook works. I have no idea why I get this issue.
```
 ciProvider:- none
 customUrl:- 
 vcsProvider:- none
 reportDirectory:- mochareports
 videoDirectory:- cypress/videos
 screenshotDirectory:- cypress/screenshots

(node:11102) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'split' of undefined
    at Object.exports.slackRunner (/home/vladmocan/unity-xp-qa/node_modules/cypress-slack-reporter/bin/slack/slack-alert.js:167:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11102) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![image](https://user-images.githubusercontent.com/19662439/122933946-c08d8080-d377-11eb-9940-19399bd53ec5.png)

**Comment by vladMocan** [comment]
My token was not stored properly.
